services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "3333:80"
      - "2525:25"

volumes:
  mongo_data:
